#!/bin/bash

function color_setup {
    local red_0=$(    tput setaf 1)
    local green_0=$(  tput setaf 2)
    local yellow_0=$( tput setaf 3)
    local blue_0=$(   tput setaf 4)
    local purple_0=$( tput setaf 5)
    local cyan_0=$(   tput setaf 6)
    local reset_0=$(  tput sgr0   )

    RED="$red_0"
    GREEN="$green_0"
    YELLOW="$yellow_0"
    BLUE="$blue_0"
    PURPLE="$purple_0"
    CYAN="$cyan_0"
    RESET="$reset_0"
}

function colorize {
    local color=$1
    local text=$2

    echo "$color$text$RESET"
}