#!/bin/bash

. "color_setup" && color_setup

PORT=5555

function wait {
    pid=$!

    spin[0]="-"
    spin[1]="\\"
    spin[2]="|"
    spin[3]="/"
    echo
    echo -n "$@ ${spin[0]}"
    while kill -0 $pid 2>/dev/null; do  
        for i in "${spin[@]}"; do
            echo -ne "\b$i"
        sleep 0.1
        done
    done
    echo
}

function getDeviceID {
    echo $(adb devices | awk -F'device' '{if (match($0, /device$/)) print $1}' | sed -e 's/[[:space:]]*$//')
}

function openDeviceConnection {
    adb wait-for-device &
        wait "Looking for USB connected device (time to connect yours)" 
    local wiredID="$(getDeviceID)"
    IP=$(adb shell ifconfig wlan0 | awk '{if (sub(/inet addr:/,"")) print $1 }')
    echo "- found device with ID $wiredID and IP $IP"

    adb tcpip $PORT 1>/dev/null &
        wait "Openning connection"
    echo "- connection open on device port $PORT"
    echo
    ID="$IP:$PORT"
}

function connect {
    read -p "Disconnect USB cable and press RETURN to continue" -n 1 -r
    echo
    if [[ -z $REPLY ]]; then
    adb connect $IP:$PORT 1>/dev/null &
        wait "Connecting to device"
    else
    connect
    fi
}

function coldIgnite {
    (adb kill-server 1>/dev/null; adb devices 1>/dev/null) &
        wait "Starting adb server"
}

function start {
    coldIgnite &&
    openDeviceConnection &&
    connect &&
    show_options
}

function disconnect_from_adb {
    adb disconnect
}

function show_status {
    printf "\033c"
    local updatedID="$(getDeviceID)"
    if [[ "$ID" == "$updatedID" ]]; then
        echo -ne "\b$(colorize $GREEN ✔) Connected to $ID"
    else
        echo -ne "\b$(colorize $RED ✘) Disconnected"
    fi
}

function show_options {
    echo `show_status`
    read -p "(s) update status | (r) restart | (q) quit" -n 1 -r
    echo
    if [[ $REPLY =~ ^[qQ]$ ]]; then
        disconnect_from_adb &&
        exit 0
    elif [[ $REPLY =~ ^[rR]$ ]]; then
        start
    elif [[ $REPLY =~ ^[sS]$ ]]; then
        show_status &&
        show_options
    else
        echo "Invalid option"
        show_options
    fi
}

start
